[package]
name = "battlesnake-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "*"
serde = { version = "1.0", features = ["derive"]}
serde_json = "*"
tokio = { version = "1.0", features = ["full"]}